blank_issues_enabled: false
contact_links:
  - name: Telegram
    url: https://t.me/iTFlatChat
    about: Please ask questions here.
  - name: Mail
    url: mailto:lmsapps2020@gmail.com
    about: Please ask questions here.
